version: '3.7'
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: docker.io/bitnami/kafka:3.7
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "messages:1:2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka2:
    image: docker.io/bitnami/kafka:3.7
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_CREATE_TOPICS: "messages:1:2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock



# https://github.com/bitnami/containers/blob/main/bitnami/zookeeper/docker-compose.yml